### ISSUE TITLE
confimap to setup jenkins permission

### ISSUE THREAD

**Issue by jlpetitlaurent** [openshift/jenkins-openshift-login-plugin#119]
Hi guys,
My environment:

- Openshift: v4.6
- Jenkins: 2.263.3
- jenkins-openshift-login-plugin: 1.0.26

My Jenkins authentication uses openshift auth2. I implemented configmap openshift-jenkins-login-plugin-config to maps every jenkins permissions. rolebinding edit, admin and view are created to an ldap groups. Every thinks work well.
```
apiVersion: v1

data:
  Agent-Build: admin
  Run-Delete: admin,edit
  Run-Replay: admin,edit
...
  View-Create: admin,edit
  View-Delete: admin,edit
  View-Read: admin,edit,view

kind: ConfigMap
metadata:
  labels:
    name: tc
  name: openshift-jenkins-login-plugin-config
  namespace: tc
```

This openshift cluster roles are very important: edit and admin. I don't want to use this role to setup jenkins rights.
I replace view, edit and admin by my new role, like this:
```
apiVersion: v1

data:
  Agent-Build: jenkins-user-jenkins-user-admin
  Run-Delete: jenkins-user-admin,jenkins-user-edit
  Run-Replay: jenkins-user-admin,jenkins-user-edit
  View-Create: jenkins-user-admin,jenkins-user-edit
  View-Delete: jenkins-user-admin,jenkins-user-edit
  View-Read: jenkins-user-admin,jenkins-user-edit,jenkins-user-view

kind: ConfigMap
metadata:
  labels:
    name: tc
  name: openshift-jenkins-login-plugin-config
  namespace: tc

```
I created new roles and rolebinding like previously with edit, admin, and view role.
I cannot logon on Jenkins

Is it possible? How can I implement this?

Regards
Jean-Louis
