### ISSUE TITLE
Could not find the openshift-jenkins-login-plugin-config config map in namespace

### ISSUE THREAD

**Issue by raballew** [openshift/jenkins-openshift-login-plugin#98]
_Jenkins Version: 2.221
OpenShift Login Plugin Version: 1.0.22_

**Description**
In order to keep the privileges limited to users that require them, I am currently trying to setup a **tester** role:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "tester"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
```

The permissions are mapped in the following config map:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: openshift-jenkins-login-plugin-config
data:
  Job-Build: "tester"
  Job-Cancel: "tester"
```
The role and the config map are located in the same namespace where the Jenkins pod runs in.

Jenkins writes the following log:
[jenkins.log](https://github.com/openshift/jenkins-openshift-login-plugin/files/4250323/jenkins.log)

Somewhere close to the end of the file you should be able to see the following message:
```
2020-02-25 12:45:18.892+0000 [id=16]	INFO	o.o.j.p.o.OpenShiftOAuth2SecurityRealm#getRoleToPermissionMap: OpenShift Jenkins Login Plugin could not find the openshift-jenkins-login-plugin-config config map in namespace NAMESPACE so the default permission mapping will be used
```
**Expected Behaviour**
The configmap should be found.
